LectureTerm.delete_all
LectureTerm.new(id: 1, term: '1年生前期').save(validate: false)
LectureTerm.new(id: 2, term: '1年生後期').save(validate: false)
LectureTerm.new(id: 3, term: '2年生前期').save(validate: false)
LectureTerm.new(id: 4, term: '2年生後期').save(validate: false)
LectureTerm.new(id: 5, term: '3年生前期').save(validate: false)
LectureTerm.new(id: 6, term: '3年生後期').save(validate: false)
LectureTerm.new(id: 7, term: '4年生前期').save(validate: false)
LectureTerm.new(id: 8, term: '4年生後期').save(validate: false)
LectureTerm.new(id: 9, term: 'その他').save(validate: false)
